name: adminSay
main: adminSay\adminSay
author: hm
version: 1.0-alpha
api:
- 1.4.1
- 1.12.0
- 1.13.0
- 2.0.0

commands:
 adminsay:
  permission: adminsay
  description: Allow commands of adminSay

permissions:
 adminsay:
  default: OP